# Use the grid engine to create a time varying spatial force field.
Database:
  image: mongo:3.0
  volumes:
    - /tmp/azrael:/data/db

RabbitMQ:
  image: rabbitmq:latest

Azrael:
  image: olitheolix/azrael:latest
  command: forcegrid
  ports:
    - "8080:8080"
    - "5555:5555"
  links:
    - Database
    - RabbitMQ

