# Create a basic Azrael stack for the demo.
# Once the stack is live point your browser to http://127.0.0.1:8080.
Database:
  image: mongo:3.0
  volumes:
    - /tmp/azrael:/data/db

RabbitMQ:
  image: rabbitmq:latest

Azrael:
  image: olitheolix/azrael:latest
  command: /demo/azrael/support/start.sh forcegrid
  ports:
    - "8080:8080"
    - "5555:5555"
  links:
    - Database
    - RabbitMQ

