name: azrael_docker
dependencies:
- certifi=14.05.14=py34_0
- cython=0.22=py34_0
- cytoolz=0.7.3=py34_0
- freetype=2.5.2=2
- ipython=3.1.0=py34_1
- jpeg=8d=0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libtiff=4.0.2=1
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pillow=2.8.1=py34_2
- pip=7.0.3=py34_0
- psutil=2.2.1=py34_0
- py=1.4.27=py34_0
- pymongo=2.8=py34_0
- pytest=2.7.1=py34_0
- python=3.4.3=1
- pyzmq=14.6.0=py34_0
- readline=6.2=2
- setuptools=17.0=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- tornado=4.2=py34_0
- xz=5.0.5=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - netifaces==0.10.4
  - setproctitle==1.1.8
  - six==1.9.0
  - websocket-client-py3==0.15.0

