name: azrael
dependencies:
- alabaster=0.7.6=py34_0
- babel=2.1.1=py34_0
- certifi=2015.9.6.2=py34_0
- cython=0.23.4=py34_0
- decorator=4.0.4=py34_0
- docutils=0.12=py34_0
- execnet=1.2.0=py34_0
- fontconfig=2.11.1=4
- freeglut=2.8.1=0
- freetype=2.5.5=0
- ipython=4.0.0=py34_0
- ipython_genutils=0.1.0=py34_0
- jinja2=2.8=py34_0
- jpeg=8d=0
- libgcc=4.8.5=1
- libgfortran=1.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libtiff=4.0.6=0
- libxml2=2.9.2=0
- markupsafe=0.23=py34_0
- matplotlib=1.4.3=np110py34_2
- networkx=1.10=py34_0
- numpy=1.10.1=py34_0
- openblas=0.2.14=3
- openssl=1.0.2d=0
- pandas=0.17.0=np110py34_0
- path.py=8.1.2=py34_0
- pep8=1.6.2=py34_0
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pillow=3.0.0=py34_1
- pip=7.1.2=py34_0
- psutil=3.2.2=py34_0
- py=1.4.30=py34_0
- pygments=2.0.2=py34_0
- pymongo=3.0.3=py34_0
- pyopengl=3.1.1a1=np110py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_0
- pytest=2.8.1=py34_0
- pytest-cache=1.0=py34_0
- python=3.4.3=2
- python-dateutil=2.4.2=py34_0
- pytz=2015.6=py34_0
- pyzmq=14.7.0=py34_1
- qt=4.8.7=1
- readline=6.2=2
- requests=2.8.1=py34_0
- setuptools=18.4=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- tornado=4.2.1=py34_0
- traitlets=4.0.0=py34_0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - netifaces==0.10.4
  - setproctitle==1.1.9
  - sphinx-rtd-theme==0.1.7
  - websocket-client-py3==0.15.0

