name: azrael
dependencies:
- astroid=1.3.4=py34_0
- cython=0.22=py34_0
- cytoolz=0.7.2=py34_0
- execnet=1.2.0=py34_0
- fontconfig=2.11.1=3
- freetype=2.5.2=1
- ipython=3.1.0=py34_0
- jpeg=8d=0
- libpng=1.5.13=1
- libsodium=0.4.5=0
- libtiff=4.0.2=1
- libxml2=2.9.0=0
- logilab-common=0.63.2=py34_0
- matplotlib=1.4.3=np19py34_1
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pandas=0.16.0=np19py34_1
- pep8=1.6.2=py34_0
- pillow=2.8.1=py34_1
- pip=6.1.1=py34_0
- psutil=2.2.1=py34_0
- py=1.4.25=py34_0
- pylint=1.4.2=py34_0
- pymongo=2.8=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.3=py34_1
- pytest=2.6.3=py34_0
- pytest-cache=1.0=py34_0
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.2=py34_0
- pyzmq=14.6.0=py34_0
- qt=4.8.6=2
- readline=6.2=2
- setuptools=15.2=py34_0
- sip=4.16.5=py34_0
- six=1.9.0=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- tornado=4.1=py34_0
- xz=5.0.5=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - netifaces==0.10.4
  - nose==1.3.4
  - pyopengl==3.1.0
  - setproctitle==1.1.8
  - websocket-client-py3==0.15.0

