name: azrael
dependencies:
- alabaster=0.7.3=py34_0
- astroid=1.3.4=py34_0
- babel=1.3=py34_0
- certifi=14.05.14=py34_0
- cython=0.22=py34_0
- cytoolz=0.7.3=py34_0
- decorator=3.4.2=py34_0
- docutils=0.12=py34_0
- execnet=1.2.0=py34_0
- fontconfig=2.11.1=4
- freetype=2.5.2=2
- ipython=3.1.0=py34_1
- jinja2=2.7.3=py34_1
- jpeg=8d=0
- libpng=1.6.17=0
- libsodium=0.4.5=0
- libtiff=4.0.2=1
- libxml2=2.9.0=0
- logilab-common=0.63.2=py34_0
- markupsafe=0.23=py34_0
- matplotlib=1.4.3=np19py34_2
- networkx=1.9.1=py34_0
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pandas=0.16.1=np19py34_0
- pep8=1.6.2=py34_0
- pillow=2.8.1=py34_2
- pip=7.0.3=py34_0
- psutil=2.2.1=py34_0
- py=1.4.25=py34_0
- pygments=2.0.2=py34_0
- pylint=1.4.2=py34_0
- pymongo=2.8=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.3=py34_1
- pytest=2.6.3=py34_0
- pytest-cache=1.0=py34_0
- python=3.4.3=1
- python-dateutil=2.4.2=py34_0
- pytz=2015.4=py34_0
- pyzmq=14.6.0=py34_0
- qt=4.8.6=3
- readline=6.2=2
- setuptools=17.1.1=py34_0
- sip=4.16.5=py34_0
- six=1.9.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- tornado=4.2=py34_0
- xz=5.0.5=0
- zeromq=4.0.5=0
- zlib=1.2.8=0
- pip:
  - netifaces==0.10.4
  - pyopengl==3.1.0
  - setproctitle==1.1.8
  - sphinx-rtd-theme==0.1.7
  - websocket-client-py3==0.15.0

