name: azrael_docker
dependencies:
- backports_abc=0.4=py34_0
- decorator=4.0.6=py34_0
- freetype=2.5.5=0
- ipython=4.0.1=py34_0
- ipython_genutils=0.1.0=py34_0
- jbig=2.1=0
- jpeg=8d=0
- jsonschema=2.4.0=py34_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libtiff=4.0.6=1
- networkx=1.10=py34_0
- numpy=1.10.2=py34_0
- openblas=0.2.14=3
- openssl=1.0.2d=0
- path.py=8.1.2=py34_1
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pillow=3.0.0=py34_1
- pip=7.1.2=py34_0
- psutil=3.3.0=py34_0
- py=1.4.30=py34_0
- pymongo=3.0.3=py34_0
- pytest=2.8.1=py34_0
- python=3.4.3=2
- pyzmq=15.1.0=py34_0
- readline=6.2=2
- requests=2.9.0=py34_0
- setuptools=19.1.1=py34_0
- simplegeneric=0.8.1=py34_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- tornado=4.3=py34_0
- traitlets=4.0.0=py34_0
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - ipython-genutils==0.1.0
  - netifaces==0.10.4
  - pika==0.10.0
  - setproctitle==1.1.9
  - six==1.10.0
  - websocket-client-py3==0.15.0

