package:
  name: assimp
  version: "azrael"

source:
  # Last version of AssImp I have tested Azrael with.
  git_url: https://github.com/olitheolix/assimp.git
  git_rev: anaconda-recipe
  
build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - gcc
    - cmake
    - libgcc

  run:
    - python
    - numpy
    - libgcc

test:
  imports:
    - pyassimp

  requires:
    - numpy

about:
    home: https://github.com/assimp/assimp
    license: Unknown
